# Generated by Django 5.2.4 on 2025-07-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0002_alter_post_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
