
"""
Auto-generated URL configuration for zone: private
Generated by Django Revolution
"""
from django.urls import path, include

# Zone-specific URL patterns for private
urlpatterns = [
    path("apix/private_api/", include("apps.private_api.urls")),
]
