
"""
Auto-generated URL configuration for zone: public
Generated by Django Revolution
"""
from django.urls import path, include

# Zone-specific URL patterns for public
urlpatterns = [
    path("apix/public_api/", include("apps.public_api.urls")),
]
