# Generated by Django 5.2.4 on 2025-07-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название канала"),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Telegram ID канала"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
                "db_table": "channels",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        max_length=100, verbose_name="Telegram ID сообщения"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата сообщения")),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "media_path",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Пути к медиа файлам"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="trading_signals.channel",
                        verbose_name="Канал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")],
                        max_length=10,
                        verbose_name="Направление",
                    ),
                ),
                ("ticker", models.CharField(max_length=20, verbose_name="Тикер")),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Цена входа"
                    ),
                ),
                (
                    "entry_price_now",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="Текущая цена входа",
                    ),
                ),
                ("leverage", models.IntegerField(verbose_name="Плечо")),
                (
                    "stop_loss",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Стоп-лосс"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Временная метка")),
                (
                    "take_profits",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Целевые цены"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="trading_signals.channel",
                        verbose_name="Канал",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="trading_signals.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Торговый сигнал",
                "verbose_name_plural": "Торговые сигналы",
                "db_table": "signals",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "date"], name="messages_channel_48fc90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["date"], name="messages_date_9d090f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("channel", "telegram_message_id")},
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["channel", "timestamp"], name="signals_channel_211588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["ticker", "timestamp"], name="signals_ticker_906a66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["direction", "timestamp"], name="signals_directi_bca4cb_idx"
            ),
        ),
    ]
