# Generated by Django 5.2.4 on 2025-07-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_signals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "Channel", "verbose_name_plural": "Channels"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="signal",
            options={
                "verbose_name": "Trading Signal",
                "verbose_name_plural": "Trading Signals",
            },
        ),
        migrations.AlterField(
            model_name="channel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Channel Name"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="telegram_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Telegram Channel ID"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="trading_signals.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(verbose_name="Message Date"),
        ),
        migrations.AlterField(
            model_name="message",
            name="media_path",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Media File Paths"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="telegram_message_id",
            field=models.CharField(max_length=100, verbose_name="Telegram Message ID"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Message Text"),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals",
                to="trading_signals.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="direction",
            field=models.CharField(
                choices=[("LONG", "Long"), ("SHORT", "Short")],
                max_length=10,
                verbose_name="Direction",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="entry_price",
            field=models.DecimalField(
                decimal_places=8, max_digits=20, verbose_name="Entry Price"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="entry_price_now",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Current Entry Price",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="leverage",
            field=models.IntegerField(verbose_name="Leverage"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals",
                to="trading_signals.message",
                verbose_name="Message",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="stop_loss",
            field=models.DecimalField(
                decimal_places=8, max_digits=20, verbose_name="Stop Loss"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="take_profits",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Take Profit Targets"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="ticker",
            field=models.CharField(max_length=20, verbose_name="Ticker"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
