# Generated by Django 5.2.4 on 2025-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_signals",
            "0002_alter_channel_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="signal",
            name="raw_json",
            field=models.TextField(blank=True, null=True, verbose_name="Raw JSON"),
        ),
        migrations.AlterField(
            model_name="message",
            name="media_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Media File Path"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="entry_price",
            field=models.FloatField(verbose_name="Entry Price"),
        ),
        migrations.AlterField(
            model_name="signal",
            name="entry_price_now",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Entry Price"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="stop_loss",
            field=models.FloatField(verbose_name="Stop Loss"),
        ),
    ]
