# Generated by Django 5.2.4 on 2025-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_signals", "0003_channel_description_signal_raw_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="raw_json",
        ),
        migrations.AlterField(
            model_name="message",
            name="media_path",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Media File Paths"
            ),
        ),
    ]
