# Generated by Django 5.2.4 on 2025-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_signals",
            "0004_remove_channel_description_remove_signal_raw_json_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="allow_signals_without_sl_tp",
            field=models.BooleanField(
                default=True, verbose_name="Allow Signals Without SL/TP"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="fails",
            field=models.IntegerField(default=0, verbose_name="Fails"),
        ),
        migrations.AddField(
            model_name="channel",
            name="forward_type",
            field=models.CharField(
                default="custom", max_length=50, verbose_name="Forward Type"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="leverage",
            field=models.IntegerField(default=1, verbose_name="Leverage"),
        ),
        migrations.AddField(
            model_name="channel",
            name="max_profit_percent",
            field=models.FloatField(default=0.0, verbose_name="Max Profit Percent"),
        ),
        migrations.AddField(
            model_name="channel",
            name="move_stop_to_breakeven",
            field=models.BooleanField(
                default=True, verbose_name="Move Stop to Breakeven"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="open_mode",
            field=models.CharField(
                default="default", max_length=50, verbose_name="Open Mode"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="portfolio_percent",
            field=models.FloatField(default=0.25, verbose_name="Portfolio Percent"),
        ),
        migrations.AddField(
            model_name="channel",
            name="position_lifetime",
            field=models.CharField(
                default="0s", max_length=20, verbose_name="Position Lifetime"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="review",
            field=models.BooleanField(default=True, verbose_name="Review"),
        ),
        migrations.AddField(
            model_name="channel",
            name="signal_fn",
            field=models.CharField(
                default="signal_analyzer",
                max_length=100,
                verbose_name="Signal Function",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="signals_only",
            field=models.BooleanField(default=True, verbose_name="Signals Only"),
        ),
        migrations.AddField(
            model_name="channel",
            name="target_chat_id",
            field=models.BigIntegerField(
                default=-4984770976, verbose_name="Target Chat ID"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="wins",
            field=models.IntegerField(default=0, verbose_name="Wins"),
        ),
        migrations.AddField(
            model_name="channel",
            name="wins_ratio",
            field=models.FloatField(default=0.0, verbose_name="Wins Ratio"),
        ),
    ]
