
"""
Auto-generated URL configuration for zone: encar_private
Generated by Django Revolution
"""
from django.urls import path, include

# Zone-specific URL patterns for encar_private
urlpatterns = [
    path("apix/data_encar/", include("src.data_encar.urls")),
]
