// This file is auto-generated by @hey-api/openapi-ts

/**
 * Serializer for Category model.
 */
export type Category = {
    readonly id: number;
    name: string;
    description?: string;
    is_active?: boolean;
};

/**
 * Serializer for Order model.
 */
export type Order = {
    readonly id: number;
    order_number: string;
    status?: StatusEnum;
    total_amount: string;
    readonly created_at: string;
    readonly items: Array<OrderItem>;
};

/**
 * Serializer for OrderItem model.
 */
export type OrderItem = {
    readonly id: number;
    product: Product;
    quantity: number;
    price: string;
};

export type PaginatedCategoryList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Category>;
};

export type PaginatedOrderItemList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<OrderItem>;
};

export type PaginatedOrderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Order>;
};

export type PaginatedProductList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Product>;
};

/**
 * Serializer for Category model.
 */
export type PatchedCategory = {
    readonly id?: number;
    name?: string;
    description?: string;
    is_active?: boolean;
};

/**
 * Serializer for Order model.
 */
export type PatchedOrder = {
    readonly id?: number;
    order_number?: string;
    status?: StatusEnum;
    total_amount?: string;
    readonly created_at?: string;
    readonly items?: Array<OrderItem>;
};

/**
 * Serializer for OrderItem model.
 */
export type PatchedOrderItem = {
    readonly id?: number;
    product?: Product;
    quantity?: number;
    price?: string;
};

/**
 * Serializer for Product model.
 */
export type PatchedProduct = {
    readonly id?: number;
    name?: string;
    description?: string;
    price?: string;
    category?: Category;
    stock?: number;
    readonly created_at?: string;
};

/**
 * Serializer for Product model.
 */
export type Product = {
    readonly id: number;
    name: string;
    description: string;
    price: string;
    category: Category;
    stock?: number;
    readonly created_at: string;
};

/**
 * * `pending` - Pending
 * * `processing` - Processing
 * * `shipped` - Shipped
 * * `delivered` - Delivered
 * * `cancelled` - Cancelled
 */
export type StatusEnum = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';

export type CategoriesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/';
};

export type CategoriesListResponses = {
    200: PaginatedCategoryList;
};

export type CategoriesListResponse = CategoriesListResponses[keyof CategoriesListResponses];

export type CategoriesCreateData = {
    body: Category;
    path?: never;
    query?: never;
    url: '/api/private_api/categories/';
};

export type CategoriesCreateResponses = {
    201: Category;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesProductsListData = {
    body?: never;
    path: {
        category_id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/{category_id}/products/';
};

export type CategoriesProductsListResponses = {
    200: PaginatedProductList;
};

export type CategoriesProductsListResponse = CategoriesProductsListResponses[keyof CategoriesProductsListResponses];

export type CategoriesProductsCreateData = {
    body: Product;
    path: {
        category_id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{category_id}/products/';
};

export type CategoriesProductsCreateResponses = {
    201: Product;
};

export type CategoriesProductsCreateResponse = CategoriesProductsCreateResponses[keyof CategoriesProductsCreateResponses];

export type CategoriesProductsDestroyData = {
    body?: never;
    path: {
        category_id: number;
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{category_id}/products/{id}/';
};

export type CategoriesProductsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CategoriesProductsDestroyResponse = CategoriesProductsDestroyResponses[keyof CategoriesProductsDestroyResponses];

export type CategoriesProductsRetrieveData = {
    body?: never;
    path: {
        category_id: number;
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{category_id}/products/{id}/';
};

export type CategoriesProductsRetrieveResponses = {
    200: Product;
};

export type CategoriesProductsRetrieveResponse = CategoriesProductsRetrieveResponses[keyof CategoriesProductsRetrieveResponses];

export type CategoriesProductsPartialUpdateData = {
    body?: PatchedProduct;
    path: {
        category_id: number;
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{category_id}/products/{id}/';
};

export type CategoriesProductsPartialUpdateResponses = {
    200: Product;
};

export type CategoriesProductsPartialUpdateResponse = CategoriesProductsPartialUpdateResponses[keyof CategoriesProductsPartialUpdateResponses];

export type CategoriesProductsUpdateData = {
    body: Product;
    path: {
        category_id: number;
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{category_id}/products/{id}/';
};

export type CategoriesProductsUpdateResponses = {
    200: Product;
};

export type CategoriesProductsUpdateResponse = CategoriesProductsUpdateResponses[keyof CategoriesProductsUpdateResponses];

export type CategoriesProductsOrderItemsListData = {
    body?: never;
    path: {
        category_id: number;
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/{category_id}/products/{id}/order_items/';
};

export type CategoriesProductsOrderItemsListResponses = {
    200: PaginatedOrderItemList;
};

export type CategoriesProductsOrderItemsListResponse = CategoriesProductsOrderItemsListResponses[keyof CategoriesProductsOrderItemsListResponses];

export type CategoriesProductsByCategoryListData = {
    body?: never;
    path: {
        category_id: number;
    };
    query?: {
        category_id?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/{category_id}/products/by_category/';
};

export type CategoriesProductsByCategoryListResponses = {
    200: PaginatedProductList;
};

export type CategoriesProductsByCategoryListResponse = CategoriesProductsByCategoryListResponses[keyof CategoriesProductsByCategoryListResponses];

export type CategoriesProductsLowStockListData = {
    body?: never;
    path: {
        category_id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/{category_id}/products/low_stock/';
};

export type CategoriesProductsLowStockListResponses = {
    200: PaginatedProductList;
};

export type CategoriesProductsLowStockListResponse = CategoriesProductsLowStockListResponses[keyof CategoriesProductsLowStockListResponses];

export type CategoriesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this category.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{id}/';
};

export type CategoriesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CategoriesDestroyResponse = CategoriesDestroyResponses[keyof CategoriesDestroyResponses];

export type CategoriesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this category.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{id}/';
};

export type CategoriesRetrieveResponses = {
    200: Category;
};

export type CategoriesRetrieveResponse = CategoriesRetrieveResponses[keyof CategoriesRetrieveResponses];

export type CategoriesPartialUpdateData = {
    body?: PatchedCategory;
    path: {
        /**
         * A unique integer value identifying this category.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{id}/';
};

export type CategoriesPartialUpdateResponses = {
    200: Category;
};

export type CategoriesPartialUpdateResponse = CategoriesPartialUpdateResponses[keyof CategoriesPartialUpdateResponses];

export type CategoriesUpdateData = {
    body: Category;
    path: {
        /**
         * A unique integer value identifying this category.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/categories/{id}/';
};

export type CategoriesUpdateResponses = {
    200: Category;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type CategoriesProductsList2Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this category.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/{id}/products/';
};

export type CategoriesProductsList2Responses = {
    200: PaginatedProductList;
};

export type CategoriesProductsList2Response = CategoriesProductsList2Responses[keyof CategoriesProductsList2Responses];

export type CategoriesActiveListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/categories/active/';
};

export type CategoriesActiveListResponses = {
    200: PaginatedCategoryList;
};

export type CategoriesActiveListResponse = CategoriesActiveListResponses[keyof CategoriesActiveListResponses];

export type OrderItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/order-items/';
};

export type OrderItemsListResponses = {
    200: PaginatedOrderItemList;
};

export type OrderItemsListResponse = OrderItemsListResponses[keyof OrderItemsListResponses];

export type OrderItemsCreateData = {
    body: OrderItem;
    path?: never;
    query?: never;
    url: '/api/private_api/order-items/';
};

export type OrderItemsCreateResponses = {
    201: OrderItem;
};

export type OrderItemsCreateResponse = OrderItemsCreateResponses[keyof OrderItemsCreateResponses];

export type OrderItemsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/order-items/{id}/';
};

export type OrderItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrderItemsDestroyResponse = OrderItemsDestroyResponses[keyof OrderItemsDestroyResponses];

export type OrderItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/order-items/{id}/';
};

export type OrderItemsRetrieveResponses = {
    200: OrderItem;
};

export type OrderItemsRetrieveResponse = OrderItemsRetrieveResponses[keyof OrderItemsRetrieveResponses];

export type OrderItemsPartialUpdateData = {
    body?: PatchedOrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/order-items/{id}/';
};

export type OrderItemsPartialUpdateResponses = {
    200: OrderItem;
};

export type OrderItemsPartialUpdateResponse = OrderItemsPartialUpdateResponses[keyof OrderItemsPartialUpdateResponses];

export type OrderItemsUpdateData = {
    body: OrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/order-items/{id}/';
};

export type OrderItemsUpdateResponses = {
    200: OrderItem;
};

export type OrderItemsUpdateResponse = OrderItemsUpdateResponses[keyof OrderItemsUpdateResponses];

export type OrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/orders/';
};

export type OrdersListResponses = {
    200: PaginatedOrderList;
};

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses];

export type OrdersCreateData = {
    body: Order;
    path?: never;
    query?: never;
    url: '/api/private_api/orders/';
};

export type OrdersCreateResponses = {
    201: Order;
};

export type OrdersCreateResponse = OrdersCreateResponses[keyof OrdersCreateResponses];

export type OrdersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{id}/';
};

export type OrdersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrdersDestroyResponse = OrdersDestroyResponses[keyof OrdersDestroyResponses];

export type OrdersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{id}/';
};

export type OrdersRetrieveResponses = {
    200: Order;
};

export type OrdersRetrieveResponse = OrdersRetrieveResponses[keyof OrdersRetrieveResponses];

export type OrdersPartialUpdateData = {
    body?: PatchedOrder;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{id}/';
};

export type OrdersPartialUpdateResponses = {
    200: Order;
};

export type OrdersPartialUpdateResponse = OrdersPartialUpdateResponses[keyof OrdersPartialUpdateResponses];

export type OrdersUpdateData = {
    body: Order;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{id}/';
};

export type OrdersUpdateResponses = {
    200: Order;
};

export type OrdersUpdateResponse = OrdersUpdateResponses[keyof OrdersUpdateResponses];

export type OrdersCancelCreateData = {
    body: Order;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{id}/cancel/';
};

export type OrdersCancelCreateResponses = {
    200: Order;
};

export type OrdersCancelCreateResponse = OrdersCancelCreateResponses[keyof OrdersCancelCreateResponses];

export type OrdersItemsListData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/orders/{id}/items/';
};

export type OrdersItemsListResponses = {
    200: PaginatedOrderItemList;
};

export type OrdersItemsListResponse = OrdersItemsListResponses[keyof OrdersItemsListResponses];

export type OrdersItemsList2Data = {
    body?: never;
    path: {
        order_id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/orders/{order_id}/items/';
};

export type OrdersItemsList2Responses = {
    200: PaginatedOrderItemList;
};

export type OrdersItemsList2Response = OrdersItemsList2Responses[keyof OrdersItemsList2Responses];

export type OrdersItemsCreateData = {
    body: OrderItem;
    path: {
        order_id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{order_id}/items/';
};

export type OrdersItemsCreateResponses = {
    201: OrderItem;
};

export type OrdersItemsCreateResponse = OrdersItemsCreateResponses[keyof OrdersItemsCreateResponses];

export type OrdersItemsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        order_id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{order_id}/items/{id}/';
};

export type OrdersItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrdersItemsDestroyResponse = OrdersItemsDestroyResponses[keyof OrdersItemsDestroyResponses];

export type OrdersItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        order_id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{order_id}/items/{id}/';
};

export type OrdersItemsRetrieveResponses = {
    200: OrderItem;
};

export type OrdersItemsRetrieveResponse = OrdersItemsRetrieveResponses[keyof OrdersItemsRetrieveResponses];

export type OrdersItemsPartialUpdateData = {
    body?: PatchedOrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        order_id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{order_id}/items/{id}/';
};

export type OrdersItemsPartialUpdateResponses = {
    200: OrderItem;
};

export type OrdersItemsPartialUpdateResponse = OrdersItemsPartialUpdateResponses[keyof OrdersItemsPartialUpdateResponses];

export type OrdersItemsUpdateData = {
    body: OrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        order_id: number;
    };
    query?: never;
    url: '/api/private_api/orders/{order_id}/items/{id}/';
};

export type OrdersItemsUpdateResponses = {
    200: OrderItem;
};

export type OrdersItemsUpdateResponse = OrdersItemsUpdateResponses[keyof OrdersItemsUpdateResponses];

export type OrdersByStatusListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
        status?: string;
    };
    url: '/api/private_api/orders/by_status/';
};

export type OrdersByStatusListResponses = {
    200: PaginatedOrderList;
};

export type OrdersByStatusListResponse = OrdersByStatusListResponses[keyof OrdersByStatusListResponses];

export type ProductsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/products/';
};

export type ProductsListResponses = {
    200: PaginatedProductList;
};

export type ProductsListResponse = ProductsListResponses[keyof ProductsListResponses];

export type ProductsCreateData = {
    body: Product;
    path?: never;
    query?: never;
    url: '/api/private_api/products/';
};

export type ProductsCreateResponses = {
    201: Product;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/products/{id}/';
};

export type ProductsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProductsDestroyResponse = ProductsDestroyResponses[keyof ProductsDestroyResponses];

export type ProductsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/products/{id}/';
};

export type ProductsRetrieveResponses = {
    200: Product;
};

export type ProductsRetrieveResponse = ProductsRetrieveResponses[keyof ProductsRetrieveResponses];

export type ProductsPartialUpdateData = {
    body?: PatchedProduct;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/products/{id}/';
};

export type ProductsPartialUpdateResponses = {
    200: Product;
};

export type ProductsPartialUpdateResponse = ProductsPartialUpdateResponses[keyof ProductsPartialUpdateResponses];

export type ProductsUpdateData = {
    body: Product;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/private_api/products/{id}/';
};

export type ProductsUpdateResponses = {
    200: Product;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type ProductsOrderItemsListData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/products/{id}/order_items/';
};

export type ProductsOrderItemsListResponses = {
    200: PaginatedOrderItemList;
};

export type ProductsOrderItemsListResponse = ProductsOrderItemsListResponses[keyof ProductsOrderItemsListResponses];

export type ProductsOrderItemsList2Data = {
    body?: never;
    path: {
        product_id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/products/{product_id}/order-items/';
};

export type ProductsOrderItemsList2Responses = {
    200: PaginatedOrderItemList;
};

export type ProductsOrderItemsList2Response = ProductsOrderItemsList2Responses[keyof ProductsOrderItemsList2Responses];

export type ProductsOrderItemsCreateData = {
    body: OrderItem;
    path: {
        product_id: number;
    };
    query?: never;
    url: '/api/private_api/products/{product_id}/order-items/';
};

export type ProductsOrderItemsCreateResponses = {
    201: OrderItem;
};

export type ProductsOrderItemsCreateResponse = ProductsOrderItemsCreateResponses[keyof ProductsOrderItemsCreateResponses];

export type ProductsOrderItemsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        product_id: number;
    };
    query?: never;
    url: '/api/private_api/products/{product_id}/order-items/{id}/';
};

export type ProductsOrderItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProductsOrderItemsDestroyResponse = ProductsOrderItemsDestroyResponses[keyof ProductsOrderItemsDestroyResponses];

export type ProductsOrderItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        product_id: number;
    };
    query?: never;
    url: '/api/private_api/products/{product_id}/order-items/{id}/';
};

export type ProductsOrderItemsRetrieveResponses = {
    200: OrderItem;
};

export type ProductsOrderItemsRetrieveResponse = ProductsOrderItemsRetrieveResponses[keyof ProductsOrderItemsRetrieveResponses];

export type ProductsOrderItemsPartialUpdateData = {
    body?: PatchedOrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        product_id: number;
    };
    query?: never;
    url: '/api/private_api/products/{product_id}/order-items/{id}/';
};

export type ProductsOrderItemsPartialUpdateResponses = {
    200: OrderItem;
};

export type ProductsOrderItemsPartialUpdateResponse = ProductsOrderItemsPartialUpdateResponses[keyof ProductsOrderItemsPartialUpdateResponses];

export type ProductsOrderItemsUpdateData = {
    body: OrderItem;
    path: {
        /**
         * A unique integer value identifying this order item.
         */
        id: number;
        product_id: number;
    };
    query?: never;
    url: '/api/private_api/products/{product_id}/order-items/{id}/';
};

export type ProductsOrderItemsUpdateResponses = {
    200: OrderItem;
};

export type ProductsOrderItemsUpdateResponse = ProductsOrderItemsUpdateResponses[keyof ProductsOrderItemsUpdateResponses];

export type ProductsByCategoryListData = {
    body?: never;
    path?: never;
    query?: {
        category_id?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/products/by_category/';
};

export type ProductsByCategoryListResponses = {
    200: PaginatedProductList;
};

export type ProductsByCategoryListResponse = ProductsByCategoryListResponses[keyof ProductsByCategoryListResponses];

export type ProductsLowStockListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/private_api/products/low_stock/';
};

export type ProductsLowStockListResponses = {
    200: PaginatedProductList;
};

export type ProductsLowStockListResponse = ProductsLowStockListResponses[keyof ProductsLowStockListResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};